services:
    postgres:
        image: postgres:14
        env_file:
            - ./docker/env/postgres.env
        ports:
            - 5432:5432
        volumes:
            - postgres_db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        env_file:
            - ./docker/env/pgadmin.env
        ports:
            - 8080:80
        volumes:
            - pgadmin_data:/var/lib/pgadmin
            - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
        depends_on:
          - postgres
volumes:
    postgres_db:
    pgadmin_data:
